# Generated by Django 5.2.5 on 2025-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
